In [ ]:

# import the relevant libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import ExtraTreesRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, accuracy_score, mean_squared_error
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('drive')

Mounted at drive


In [ ]:
path = "/content/drive/MyDrive/Pradeep_redpine/Documents/"
master_data= pd.read_csv(path + 'master_data.csv')

master_data.head()

a         b         c         d  ...        aq        ar        as  label
0  0.759328  0.051102  0.050447  0.691667  ...  0.009824  8.935547  0.003691    109
1  0.901039  0.236481  0.234768  0.666667  ...  0.015067  7.910156  0.010668    109
2  0.881105  0.172121  0.164977  0.665000  ...  0.013072  9.741211  0.004527    109
3  0.849716  0.135928  0.135301  0.683333  ...  0.008889  9.301758  0.005885    109
4  0.825774  0.139097  0.128035  0.675000  ...  0.011704  9.448242  0.006146    109

[5 rows x 46 columns]

In [ ]:
X=master_data.iloc[:,0:46][0:].to_numpy()

y=master_data.iloc[:,-1][0:].to_numpy()
y=y.reshape(-1,1)

len(X),len(y)

(408, 408)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor

import numpy as np
import pandas as pd
import statsmodels.stats.api as sm

%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [ ]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((285, 46), (123, 46), (285, 1), (123, 1))

In [ ]:
# feature scale the X_train and X_test values

norm = MinMaxScaler().fit(X_train)

# transform training data
X_train = norm.transform(X_train)

# transform testing data
X_test = norm.transform(X_test)

print(X_train)
print('\n')
print(X_test)

[[0.51864708 0.41490795 0.62993522 ... 0.36563877 0.62977069 0.5026455 ]
 [0.79256499 0.49053953 0.7432467  ... 0.84140969 0.08344809 0.5026455 ]
 [0.82753212 0.23339861 0.35794949 ... 0.57709251 0.27015316 0.5026455 ]
 ...
 [0.35093697 0.755425   0.19121413 ... 0.13656388 0.46597756 0.45502646]
 [0.33385352 0.89228718 0.48711267 ... 0.16740088 0.71614851 0.49206349]
 [0.87071562 0.57492286 0.85517703 ... 0.58590308 0.31233594 0.5026455 ]]


[[0.61668503 0.83991695 0.31243534 ... 0.21585903 0.32047941 0.5026455 ]
 [0.8700178  0.04716578 0.08004118 ... 0.75330396 0.04878105 1.        ]
 [0.25791425 0.48628774 0.72599853 ... 0.45374449 0.238482   0.50793651]
 ...
 [0.49021101 0.80190496 0.24425928 ... 0.17180617 0.41283788 0.52910053]
 [0.57669563 0.09297307 0.14913254 ... 0.55947137 0.16715335 1.        ]
 [0.56030414 0.83280001 0.32059438 ... 0.14977974 0.37655827 0.52910053]]


In [ ]:

# Fitting extra trees regressor

etr = ExtraTreesRegressor(random_state = 123 , max_depth = 45  , n_estimators = 400)
etr.fit(X_train,y_train)

ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=45, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=400, n_jobs=None, oob_score=False,
                    random_state=123, verbose=0, warm_start=False)

In [ ]:

#Fitting light gbm model on the train data

lgbm = LGBMRegressor(random_state = 123 ,  num_leaves = 750 , learning_rate = 0.01, max_bin = 1200 , n_estimators = 1000)
lgbm.fit(X_train,y_train)

LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.01, max_bin=1200,
              max_depth=-1, min_child_samples=20, min_child_weight=0.001,
              min_split_gain=0.0, n_estimators=1000, n_jobs=-1, num_leaves=750,
              objective=None, random_state=123, reg_alpha=0.0, reg_lambda=0.0,
              silent=True, subsample=1.0, subsample_for_bin=200000,
              subsample_freq=0)

In [ ]:
#Fitting xgboost regressor model on the train data

xgb = XGBRegressor(random_state = 123 , max_depth = 7 , learning_rate = 0.2 , n_estimators = 1500)
xgb.fit(X_train,y_train)

[08:06:30] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.2, max_delta_step=0,
             max_depth=7, min_child_weight=1, missing=None, n_estimators=1500,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=123,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:

#Fitting random forest regressor model on the train data

rf = RandomForestRegressor(random_state = 123 , max_depth = 45 , n_estimators = 600)
rf.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=45, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=600, n_jobs=None, oob_score=False,
                      random_state=123, verbose=0, warm_start=False)

In [ ]:
#!pip install catboost


In [ ]:
#Fitting catboost regressor model on the train data
#from catboost import CatBoostRegressor
#cat = CatBoostRegressor(random_state = 123  , max_depth = 14 )
#cat.fit(X_train,y_train, verbose = False)

In [ ]:
train_score = pd.DataFrame({
    'model': ['ExtraTreesRegressor', 'LGBMRegressor', 'XGBRegressor', 'RandomForestRegressor'],# 'CatBoostRegressor'],
    
    'score': [etr.score(X_train, y_train), lgbm.score(X_train, y_train),
                xgb.score(X_train, y_train) , rf.score(X_train, y_train)]
              #  cat.score(X_train, y_train)]
    })
train_score

model     score
0    ExtraTreesRegressor  1.000000
1          LGBMRegressor  0.985840
2           XGBRegressor  1.000000
3  RandomForestRegressor  0.996648

In [ ]:
etr_pred = etr.predict(X_test)
lgbm_pred = lgbm.predict(X_test)
xgb_pred = xgb.predict(X_test)
rf_pred = rf.predict(X_test)
#cat_pred = cat.predict(X_test)

In [ ]:
# Generalisation
best_model = pd.DataFrame({
    'model': ['ExtraTreesRegressor', 'LGBMRegressor', 'XGBRegressor', 'RandomForestRegressor'],# 'CatBoostRegressor'],
    
    'mae': [mean_absolute_error(y_test, etr_pred), mean_absolute_error(y_test, lgbm_pred),
           mean_absolute_error(y_test, xgb_pred), mean_absolute_error(y_test, rf_pred)],
           #mean_absolute_error(y_test, cat_pred)],
    
    'mse': [mean_squared_error(y_test, etr_pred), mean_squared_error(y_test, lgbm_pred),
            mean_squared_error(y_test, xgb_pred), mean_squared_error(y_test, rf_pred)],
           # mean_squared_error(y_test, cat_pred)],
    
    'rmse': [(np.sqrt(metrics.mean_squared_error(y_test, etr_pred))),(np.sqrt(metrics.mean_squared_error(y_test, lgbm_pred))),
             (np.sqrt(metrics.mean_squared_error(y_test, xgb_pred))), (np.sqrt(metrics.mean_squared_error(y_test, rf_pred)))]#,
            # (np.sqrt(metrics.mean_squared_error(y_test, cat_pred)))]
})
best_model

model       mae       mse      rmse
0    ExtraTreesRegressor  0.105305  0.079475  0.281912
1          LGBMRegressor  0.512012  1.008166  1.004075
2           XGBRegressor  0.091488  0.274853  0.524264
3  RandomForestRegressor  0.151653  0.378380  0.615126

In [ ]:
#create the grid
grid = {'max_depth': [3,4,5],'n_estimators':[100, 200, 300]}

#Instantiate GridSearchCV
model = GridSearchCV (estimator = xgb, param_grid = grid, scoring ='neg_root_mean_squared_error', cv = 5)


In [ ]:
model.fit(X_train,y_train)

[08:13:55] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:13:55] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:13:55] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:13:56] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:13:56] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:13:56] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:13:56] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:13:56] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of re

GridSearchCV(cv=5, error_score=nan,
             estimator=XGBRegressor(base_score=0.5, booster='gbtree',
                                    colsample_bylevel=1, colsample_bynode=1,
                                    colsample_bytree=1, gamma=0,
                                    importance_type='gain', learning_rate=0.2,
                                    max_delta_step=0, max_depth=7,
                                    min_child_weight=1, missing=None,
                                    n_estimators=1500, n_jobs=1, nthread=None,
                                    objective='reg:linear', random_state=123,
                                    reg_alpha=0, reg_lambda=1,
                                    scale_pos_weight=1, seed=None, silent=None,
                                    subsample=1, verbosity=1),
             iid='deprecated', n_jobs=None,
             param_grid={'max_depth': [3, 4, 5],
                         'n_estimators': [100, 200, 300]},
             pre_disp

In [ ]:
y_pred = model.predict(X_test)


In [ ]:
grid_model = pd.DataFrame({
    'model': ['XGBRegressor'],
    'mae': [mean_absolute_error(y_test, y_pred)],
    'mse': [mean_squared_error(y_test, y_pred)],
    'rmse': [np.sqrt(metrics.mean_squared_error(y_test, y_pred))]
    })
grid_model

model      mae       mse      rmse
0  XGBRegressor  0.09626  0.266114  0.515863